/**
 * Starter decks by job, shipped with the app.
 *
 * The sharing feature people actually want is "let me use the deck someone in
 * my job already made". This is that, minus the backend — and minus the
 * privacy problem, because nothing here came out of anybody's real chat room.
 * They are written the way a Korean office worker actually types on KakaoTalk:
 * short, 존댓말, half-finished sentences — paired with the English a native
 * speaker would use in the same spot, not the textbook version.
 *
 * Each card keeps one line of context for the same reason personal cards do:
 * "그거" only makes sense when you can see what was said before it.
 *
 * When user contributions arrive, they land in this same shape: a Korean line,
 * an English line, a situation tag. Never a conversation log.
 */

export const JOB_DECKS = [
  {
    id: 'common',
    name: '공통',
    blurb: '보고, 요청, 일정 조율, 사과',
    cards: [
      { ko: '확인하고 바로 말씀드릴게요', en: 'Let me check and get right back to you.', situation: '확인 약속', context: [{ speaker: '팀장', text: '이거 언제까지 될까요?' }] },
      { ko: '넵 확인했습니다', en: 'Got it, thanks.', situation: '수신 확인', context: [{ speaker: '팀장', text: '방금 메일 보냈어요' }] },
      { ko: '죄송한데 조금만 늦어질 것 같아요', en: "Sorry, it's going to run a little late.", situation: '지연 알림', context: [{ speaker: '팀장', text: '오늘 마감이죠?' }] },
      { ko: '혹시 내일로 미뤄도 될까요?', en: 'Would tomorrow work instead?', situation: '일정 변경', context: [{ speaker: '동료', text: '오늘 오후에 잠깐 볼까요?' }] },
      { ko: '지금 다른 거 하고 있어서 좀 있다 볼게요', en: "I'm in the middle of something — I'll take a look shortly.", situation: '보류', context: [{ speaker: '동료', text: '이거 한 번만 봐주실 수 있어요?' }] },
      { ko: '그 건은 제가 맡을게요', en: "I'll take that one.", situation: '업무 수락', context: [{ speaker: '팀장', text: '이거 누가 하실래요?' }] },
      { ko: '혹시 지금 통화 가능하세요?', en: 'Do you have a minute for a quick call?', situation: '통화 요청', context: [] },
      { ko: '자료 공유드립니다', en: 'Sharing the files here.', situation: '자료 전달', context: [] },
      { ko: '이 부분은 제가 잘 몰라서요', en: "That's outside what I know well.", situation: '한계 인정', context: [{ speaker: '동료', text: '이거 어떻게 하는지 아세요?' }] },
      { ko: '고생하셨습니다', en: 'Nice work today.', situation: '격려', context: [] },
      { ko: '먼저 들어가 보겠습니다', en: "I'm heading out — see you tomorrow.", situation: '퇴근 인사', context: [] },
      { ko: '다시 한 번만 설명해 주실 수 있을까요?', en: 'Could you walk me through that once more?', situation: '재설명 요청', context: [{ speaker: '팀장', text: '아까 회의에서 말한 대로 진행하시면 돼요' }] },
      { ko: '지금 자리에 없어서 이따 확인할게요', en: "I'm away from my desk — I'll check in a bit.", situation: '부재 응답', context: [{ speaker: '팀장', text: '지금 잠깐 볼 수 있어요?' }] },
      { ko: '오늘 재택입니다', en: "I'm working from home today.", situation: '근무 형태', context: [] },
      { ko: '내일 연차라 못 볼 것 같아요', en: "I'm off tomorrow, so I won't be around.", situation: '휴가 알림', context: [{ speaker: '동료', text: '내일 오후에 같이 볼까요?' }] },
      { ko: '잠깐 자리 비웠습니다', en: 'Sorry, I stepped away for a second.', situation: '부재 사과', context: [{ speaker: '팀장', text: '어디 계세요?' }] },
      { ko: '회의 5분만 늦을게요', en: "I'll be about five minutes late.", situation: '지각 알림', context: [] },
      { ko: '링크 다시 보내주실 수 있어요?', en: 'Could you send the link again?', situation: '재전송 요청', context: [] },
      { ko: '소리가 잘 안 들려요', en: "I can't hear you very well.", situation: '통화 문제', context: [] },
      { ko: '화면 공유 해주실 수 있을까요?', en: 'Could you share your screen?', situation: '공유 요청', context: [] },
      { ko: '제가 정리해서 공유드릴게요', en: "I'll write it up and share it.", situation: '정리 약속', context: [{ speaker: '팀장', text: '오늘 얘기한 거 누가 정리하죠?' }] },
      { ko: '확인했는데 문제 없어 보입니다', en: 'I checked and it looks fine to me.', situation: '확인 결과', context: [{ speaker: '동료', text: '이거 좀 이상한 것 같지 않아요?' }] },
      { ko: '제 쪽에서는 문제 없습니다', en: "Nothing's blocking on my end.", situation: '상태 보고', context: [] },
      { ko: '이건 제 담당이 아니라서요', en: "That's not really my area.", situation: '담당 구분', context: [{ speaker: '동료', text: '이거 처리 좀 부탁드려요' }] },
      { ko: '담당자분께 여쭤볼게요', en: 'Let me ask the person who owns it.', situation: '이관 예고', context: [] },
      { ko: '급한 건 아니에요 천천히 주셔도 됩니다', en: 'No rush on this one.', situation: '여유 안내', context: [] },
      { ko: '가능하면 오늘 중으로 부탁드려요', en: 'If you can, sometime today would help.', situation: '마감 요청', context: [] },
      { ko: '언제까지 필요하신지 알려주세요', en: 'Let me know when you need it by.', situation: '마감 확인', context: [{ speaker: '동료', text: '이거 하나만 봐주실 수 있어요?' }] },
      { ko: '아까 말씀하신 거 맞나요?', en: 'Is this what you meant earlier?', situation: '이해 확인', context: [] },
      { ko: '제가 잘못 이해했네요', en: 'I misunderstood — my mistake.', situation: '오해 정정', context: [{ speaker: '팀장', text: '그게 아니라 반대로요' }] },
      { ko: '알려주셔서 감사합니다', en: 'Thanks for the heads-up.', situation: '감사', context: [] },
      { ko: '덕분에 잘 마무리했습니다', en: 'Thanks to you, we got it wrapped up.', situation: '감사', context: [] },
      { ko: '이번 주는 좀 빡빡할 것 같아요', en: "This week's pretty packed for me.", situation: '여유 없음', context: [{ speaker: '동료', text: '이번 주에 시간 되세요?' }] },
      { ko: '다음 주에 다시 얘기해도 될까요?', en: 'Can we pick this up next week?', situation: '연기 요청', context: [] },
      { ko: '방금 보내드렸습니다', en: 'Just sent it over.', situation: '전달 완료', context: [{ speaker: '팀장', text: '자료 언제 주시나요?' }] },
      { ko: '메일 확인 부탁드립니다', en: 'Please take a look at the email when you get a chance.', situation: '확인 요청', context: [] },
      { ko: '혹시 놓친 부분 있으면 말씀해 주세요', en: 'Let me know if I missed anything.', situation: '보완 요청', context: [] },
      { ko: '저는 괜찮습니다', en: 'Works for me.', situation: '동의', context: [{ speaker: '팀장', text: '목요일 3시로 할까요?' }] },
      { ko: '어느 쪽이든 상관없어요', en: 'Either way works for me.', situation: '선택 위임', context: [{ speaker: '동료', text: '화요일이랑 수요일 중에 언제가 나아요?' }] },
      { ko: '내일 아침에 다시 보겠습니다', en: "I'll pick it back up first thing tomorrow.", situation: '다음 일정', context: [] },
    ],
  },

  {
    id: 'dev',
    name: '개발',
    blurb: '배포, 장애 대응, 코드 리뷰',
    cards: [
      { ko: '지금 QA 돌리고 있습니다', en: "I'm running QA on it now.", situation: '진행 보고', context: [{ speaker: '팀장', text: '그 배포 건 어떻게 됐어요?' }] },
      { ko: '로컬에선 되는데 서버에서만 나네요', en: "It works locally — it's only failing on the server.", situation: '증상 설명', context: [{ speaker: '동료', text: '저는 재현이 안 되는데요?' }] },
      { ko: '롤백하겠습니다', en: "I'm rolling it back.", situation: '장애 대응', context: [{ speaker: '팀장', text: '지금 서비스 터진 것 같은데요' }] },
      { ko: '원인 파악되면 공유드릴게요', en: "I'll share the root cause once I have it.", situation: '후속 약속', context: [] },
      { ko: '리뷰 부탁드립니다', en: 'Could you take a look at this PR?', situation: '리뷰 요청', context: [] },
      { ko: '코멘트 반영했습니다', en: "I've addressed your comments.", situation: '수정 완료', context: [{ speaker: '리뷰어', text: '몇 개 코멘트 남겼어요' }] },
      { ko: '이건 좀 크게 고쳐야 할 것 같은데요', en: 'I think this needs a bigger change than that.', situation: '이견 제시', context: [{ speaker: '동료', text: '여기만 살짝 고치면 되지 않나요?' }] },
      { ko: '스펙이 좀 애매해서 확인이 필요합니다', en: "The spec is ambiguous here — I need to confirm before I build it.", situation: '요구사항 확인', context: [] },
      { ko: '배포 완료했습니다', en: "The deploy's done.", situation: '완료 보고', context: [] },
      { ko: '테스트 통과했습니다', en: 'All tests are green.', situation: '검증 보고', context: [] },
      { ko: '이거 기존 코드도 같이 깨질 수 있어요', en: 'This could break existing behavior too.', situation: '리스크 경고', context: [] },
      { ko: '일정 다시 잡아야 할 것 같습니다', en: 'I think we need to reset the timeline on this.', situation: '일정 재협의', context: [{ speaker: '팀장', text: '이번 주까지 가능하죠?' }] },
      { ko: '재현이 안 되는데 혹시 어떤 환경이세요?', en: "I can't reproduce it — what environment are you on?", situation: '재현 확인', context: [{ speaker: '동료', text: '저는 계속 에러 나는데요' }] },
      { ko: '로그 좀 보내주실 수 있을까요?', en: 'Could you send me the logs?', situation: '로그 요청', context: [] },
      { ko: '이슈로 올려주시면 확인하겠습니다', en: "File an issue and I'll take a look.", situation: '접수 안내', context: [] },
      { ko: '지금 원인 보고 있습니다', en: "I'm digging into it now.", situation: '조사 중', context: [{ speaker: '팀장', text: '어떻게 되어가고 있어요?' }] },
      { ko: '캐시 때문인 것 같아요', en: "I think it's a caching issue.", situation: '원인 추정', context: [] },
      { ko: '임시로 막아두겠습니다', en: "I'll put a temporary fix in.", situation: '임시 조치', context: [] },
      { ko: '근본 원인은 따로 고쳐야 합니다', en: 'The real fix has to come separately.', situation: '후속 필요', context: [] },
      { ko: '머지해도 될까요?', en: 'Is this good to merge?', situation: '머지 확인', context: [] },
      { ko: '컨플릭트 정리하고 다시 올릴게요', en: "I'll resolve the conflicts and push again.", situation: '충돌 해결', context: [{ speaker: '리뷰어', text: '지금 충돌 나 있어요' }] },
      { ko: '브랜치 최신으로 맞춰주세요', en: 'Could you rebase on the latest?', situation: '정리 요청', context: [] },
      { ko: '테스트 하나 깨져 있어요', en: "There's one failing test.", situation: '실패 보고', context: [] },
      { ko: 'CI 다시 돌려볼게요', en: 'Let me re-run CI.', situation: '재시도', context: [] },
      { ko: '이 부분은 나중에 리팩터링하죠', en: "Let's refactor this part later.", situation: '후순위', context: [] },
      { ko: '지금 고치면 리스크가 커요', en: 'Changing it now is riskier than leaving it.', situation: '리스크 설명', context: [{ speaker: '팀장', text: '이번에 같이 고치면 안 돼요?' }] },
      { ko: '문서에 정리해 두겠습니다', en: "I'll document it.", situation: '문서화', context: [] },
      { ko: '서버 재시작했습니다', en: 'I restarted the server.', situation: '조치 보고', context: [] },
      { ko: '배포는 내일 아침에 하겠습니다', en: "I'll ship it tomorrow morning.", situation: '배포 일정', context: [] },
      { ko: '금요일 배포는 피하고 싶어요', en: "I'd rather not deploy on a Friday.", situation: '배포 이견', context: [{ speaker: '팀장', text: '오늘 중으로 내보낼 수 있을까요?' }] },
      { ko: '모니터링 붙여두겠습니다', en: "I'll add monitoring for it.", situation: '예방 조치', context: [] },
      { ko: '영향 범위 확인 중입니다', en: "I'm checking what else this touches.", situation: '영향 파악', context: [] },
      { ko: '이건 프론트 쪽 이슈 같아요', en: 'This looks like a front-end issue.', situation: '원인 구분', context: [] },
      { ko: 'API 스펙 좀 공유해 주실 수 있나요?', en: 'Could you share the API spec?', situation: '자료 요청', context: [] },
      { ko: '응답이 좀 느린데 확인 부탁드려요', en: 'Responses are slow — could you take a look?', situation: '성능 문제', context: [] },
      { ko: '데이터 백업해두고 진행하겠습니다', en: "I'll back up the data before I touch it.", situation: '사전 조치', context: [] },
      { ko: '이 티켓은 제가 가져갈게요', en: "I'll pick up this ticket.", situation: '업무 수락', context: [] },
      { ko: '예상보다 오래 걸릴 것 같습니다', en: 'This is going to take longer than I thought.', situation: '일정 지연', context: [] },
      { ko: '마이그레이션은 점검 시간에 하겠습니다', en: "I'll run the migration during the maintenance window.", situation: '작업 일정', context: [] },
      { ko: '승인해 주시면 바로 진행하겠습니다', en: "Once you approve, I'll go ahead.", situation: '승인 요청', context: [] },
    ],
  },

  {
    id: 'sales',
    name: '영업·세일즈',
    blurb: '미팅 제안, 견적, 팔로업',
    cards: [
      { ko: '다음 주 중에 미팅 한 번 잡을 수 있을까요?', en: 'Could we set up a meeting sometime next week?', situation: '미팅 제안', context: [] },
      { ko: '견적서 보내드렸습니다 확인 부탁드려요', en: "I've sent over the quote — let me know what you think.", situation: '견적 전달', context: [] },
      { ko: '내부 검토 후에 다시 연락드리겠습니다', en: "I'll check internally and get back to you.", situation: '보류 응답', context: [{ speaker: '고객', text: '이 가격에서 조금 더 안 될까요?' }] },
      { ko: '혹시 진행 상황 여쭤봐도 될까요?', en: 'Just checking in — any update on your end?', situation: '팔로업', context: [] },
      { ko: '그 부분은 조정 가능합니다', en: "We have some flexibility there.", situation: '협상', context: [{ speaker: '고객', text: '계약 기간이 좀 부담스러워서요' }] },
      { ko: '죄송하지만 그건 어려울 것 같습니다', en: "I'm afraid that's not something we can do.", situation: '정중한 거절', context: [] },
      { ko: '조건 정리해서 다시 보내드릴게요', en: "I'll put the terms together and send them over.", situation: '후속 조치', context: [] },
      { ko: '이번 건은 저희 쪽에서 맞춰보겠습니다', en: "We'll work with you on this one.", situation: '양보', context: [] },
      { ko: '결정까지 시간이 얼마나 필요하실까요?', en: 'How much time do you need to decide?', situation: '일정 확인', context: [] },
      { ko: '좋은 소식 기다리고 있겠습니다', en: "Looking forward to hearing from you.", situation: '마무리 인사', context: [] },
      { ko: '담당자분 연결해 주실 수 있을까요?', en: 'Could you put me in touch with the right person?', situation: '연결 요청', context: [] },
      { ko: '계약서 검토 중입니다', en: "We're reviewing the contract now.", situation: '진행 보고', context: [] },
      { ko: '편하신 시간 알려주시면 맞추겠습니다', en: "Let me know what time works and I'll fit around it.", situation: '일정 조율', context: [] },
      { ko: '온라인으로 뵈어도 괜찮을까요?', en: 'Would a video call work instead?', situation: '미팅 형식', context: [] },
      { ko: '자료 미리 보내드릴게요', en: "I'll send the deck over beforehand.", situation: '사전 자료', context: [] },
      { ko: '오늘 시간 내주셔서 감사합니다', en: 'Thanks for making time today.', situation: '감사', context: [] },
      { ko: '말씀 주신 부분 내부에 전달하겠습니다', en: "I'll pass that along to my team.", situation: '전달 약속', context: [{ speaker: '고객', text: '이 부분은 좀 아쉽네요' }] },
      { ko: '예산은 어느 정도 생각하고 계신가요?', en: 'What kind of budget are you working with?', situation: '예산 확인', context: [] },
      { ko: '도입 시기는 언제쯤 보고 계세요?', en: 'When are you looking to get started?', situation: '일정 확인', context: [] },
      { ko: '비슷한 사례가 있어서 공유드릴게요', en: "We've done something similar — let me share it.", situation: '사례 공유', context: [] },
      { ko: '지금 결정 안 하셔도 됩니다', en: "There's no pressure to decide today.", situation: '부담 완화', context: [] },
      { ko: '계약 전에 한 번 더 정리해 드릴게요', en: "I'll recap everything before we sign.", situation: '사전 정리', context: [] },
      { ko: '조건은 문서로 남겨두겠습니다', en: "I'll get the terms in writing.", situation: '문서화', context: [] },
      { ko: '이 부분은 제가 확답 드리기 어렵습니다', en: "I can't commit to that on my own.", situation: '권한 밖', context: [{ speaker: '고객', text: '지금 바로 확정해 주실 수 있나요?' }] },
      { ko: '확인 후에 말씀드리겠습니다', en: "I'll confirm internally and get back to you.", situation: '확인 약속', context: [] },
      { ko: '이번 분기 안에 마무리하고 싶습니다', en: "We'd like to close this within the quarter.", situation: '목표 공유', context: [] },
      { ko: '혹시 걸리는 부분 있으실까요?', en: 'Is there anything giving you pause?', situation: '우려 확인', context: [] },
      { ko: '다른 곳도 함께 보고 계실까요?', en: 'Are you looking at other options as well?', situation: '경쟁 확인', context: [] },
      { ko: '저희 강점은 여기에 있습니다', en: "This is where we're strongest.", situation: '강점 설명', context: [] },
      { ko: '무리한 약속은 드리지 않겠습니다', en: "I won't promise something we can't deliver.", situation: '신뢰 확보', context: [] },
      { ko: '샘플 먼저 써보시는 건 어떠세요?', en: 'Would you like to start with a trial?', situation: '제안', context: [] },
      { ko: '계약서 초안 보내드렸습니다', en: "I've sent the draft contract.", situation: '전달 완료', context: [] },
      { ko: '서명본 회신 부탁드립니다', en: 'Could you send back the signed copy?', situation: '회신 요청', context: [] },
      { ko: '결제 조건은 협의 가능합니다', en: 'Payment terms are negotiable.', situation: '협상', context: [] },
      { ko: '세금계산서는 월말에 발행됩니다', en: 'The invoice goes out at the end of the month.', situation: '정산 안내', context: [] },
      { ko: '담당이 바뀌어서 인사드립니다', en: "I'm taking over this account — good to meet you.", situation: '담당 인계', context: [] },
      { ko: '연락이 늦어 죄송합니다', en: 'Sorry for the slow reply.', situation: '사과', context: [] },
      { ko: '다시 연락 주셔서 감사합니다', en: 'Thanks for getting back to me.', situation: '감사', context: [] },
      { ko: '이번엔 인연이 아니었던 것 같습니다', en: "Sounds like the timing isn't right this time.", situation: '실주 응대', context: [{ speaker: '고객', text: '이번엔 다른 곳으로 결정했습니다' }] },
      { ko: '다음 기회에 다시 뵙겠습니다', en: 'Hope we get another chance to work together.', situation: '마무리', context: [] },
    ],
  },

  {
    id: 'pm',
    name: '기획·PM',
    blurb: '우선순위, 범위, 이해관계자 조율',
    cards: [
      { ko: '우선순위 다시 정리해야 할 것 같아요', en: 'I think we need to re-prioritize.', situation: '우선순위 조정', context: [{ speaker: '팀장', text: '이것도 이번 스프린트에 넣을 수 있나요?' }] },
      { ko: '이번 스프린트엔 안 들어갈 것 같습니다', en: "That won't make it into this sprint.", situation: '범위 방어', context: [] },
      { ko: '요구사항 정리해서 문서로 공유드릴게요', en: "I'll write up the requirements and share the doc.", situation: '문서화 약속', context: [] },
      { ko: '이거 왜 필요한지 조금 더 설명해 주실 수 있어요?', en: 'Could you help me understand why we need this?', situation: '배경 확인', context: [{ speaker: '기획자', text: '이 기능 추가해 주세요' }] },
      { ko: '개발팀이랑 먼저 얘기해 볼게요', en: "Let me talk it over with engineering first.", situation: '조율 예고', context: [] },
      { ko: '지금 일정으로는 무리입니다', en: "That's not realistic with the current timeline.", situation: '일정 이견', context: [] },
      { ko: '어디까지 꼭 필요한지 정해야 할 것 같아요', en: 'We should agree on what actually has to be in scope.', situation: '범위 합의', context: [] },
      { ko: '중간에 한 번 같이 보시죠', en: "Let's check in partway through.", situation: '중간 점검 제안', context: [] },
      { ko: '그럼 그렇게 진행하겠습니다', en: "Alright, we'll go with that.", situation: '결정 확정', context: [] },
      { ko: '결정 사항 정리해서 올려두겠습니다', en: "I'll write up what we decided and post it.", situation: '기록', context: [] },
      { ko: '이해관계자들한테 먼저 공유해야 할 것 같아요', en: 'We should loop in the stakeholders before we move.', situation: '사전 공유', context: [] },
      { ko: '다음 스텝이 뭔지 정하고 끝내죠', en: "Let's agree on next steps before we wrap up.", situation: '회의 마무리', context: [] },
      { ko: '지금 들어온 요청이 세 개인데 순서를 정해야 해요', en: 'We have three requests in flight — we need an order.', situation: '우선순위', context: [] },
      { ko: '이번 주에 꼭 되어야 하는 건 하나입니다', en: 'Only one of these truly has to land this week.', situation: '범위 압축', context: [] },
      { ko: '나머지는 다음으로 미루겠습니다', en: 'The rest moves to the next round.', situation: '연기 결정', context: [] },
      { ko: '기획서 초안 공유드립니다', en: 'Sharing the first draft of the spec.', situation: '문서 공유', context: [] },
      { ko: '의견 있으시면 문서에 코멘트 남겨주세요', en: 'Drop your comments in the doc.', situation: '피드백 요청', context: [] },
      { ko: '금요일까지 의견 없으시면 확정하겠습니다', en: "If I don't hear back by Friday, I'll treat it as final.", situation: '마감 공지', context: [] },
      { ko: '목표가 뭔지 다시 맞춰보죠', en: "Let's get aligned on what we're actually trying to do.", situation: '목표 정렬', context: [] },
      { ko: '성공 기준을 어떻게 잡을까요?', en: 'How should we define success here?', situation: '지표 합의', context: [] },
      { ko: '숫자로 확인할 방법이 있을까요?', en: 'Is there a way to measure that?', situation: '측정 확인', context: [{ speaker: '팀장', text: '이게 잘 되고 있는 건가요?' }] },
      { ko: '이건 가설이라 검증이 필요합니다', en: 'This is an assumption — we need to test it.', situation: '가설 구분', context: [] },
      { ko: '작게 먼저 해보는 게 어떨까요?', en: 'What if we start small?', situation: '축소 제안', context: [] },
      { ko: '리스크는 여기 하나입니다', en: "There's one real risk here.", situation: '리스크 정리', context: [] },
      { ko: '일정이 밀리면 바로 공유드리겠습니다', en: "If the timeline slips, I'll flag it right away.", situation: '투명성', context: [] },
      { ko: '회의 전에 안건 공유드릴게요', en: "I'll send the agenda before the meeting.", situation: '사전 안내', context: [] },
      { ko: '30분이면 충분할 것 같습니다', en: 'Thirty minutes should be enough.', situation: '시간 제안', context: [] },
      { ko: '오늘 회의는 결정만 하고 끝내죠', en: "Let's use today just to decide.", situation: '회의 운영', context: [] },
      { ko: '그건 이 자리에서 결정할 수 없습니다', en: "We can't settle that in this room.", situation: '결정 보류', context: [] },
      { ko: '누가 이걸 맡을지 정하죠', en: "Let's name an owner for this.", situation: '담당 지정', context: [] },
      { ko: '제가 챙기겠습니다', en: "I'll own it.", situation: '책임 수락', context: [{ speaker: '팀장', text: '이건 누가 챙기죠?' }] },
      { ko: '개발 공수 어느 정도 될까요?', en: 'How much effort would this take on your side?', situation: '공수 확인', context: [] },
      { ko: '디자인 먼저 나와야 시작할 수 있어요', en: "We can't start until the design lands.", situation: '선행 조건', context: [] },
      { ko: '요구사항이 바뀌었습니다', en: 'The requirements changed.', situation: '변경 공지', context: [] },
      { ko: '바뀐 부분만 정리해서 드릴게요', en: "I'll send just what changed.", situation: '차이 정리', context: [] },
      { ko: '이번 릴리스에서 빠집니다', en: 'This is dropping from the release.', situation: '범위 제외', context: [] },
      { ko: '사용자 입장에서 한 번 보죠', en: "Let's look at it from the user's side.", situation: '관점 전환', context: [] },
      { ko: '데이터 먼저 보고 정하겠습니다', en: "I'd like to see the numbers before we decide.", situation: '근거 요구', context: [] },
      { ko: '지난번 결정과 충돌합니다', en: 'This conflicts with what we decided last time.', situation: '일관성', context: [] },
      { ko: '정리해서 다시 올리겠습니다', en: "I'll clean this up and repost it.", situation: '재정리', context: [] },
    ],
  },

  {
    id: 'design',
    name: '디자인',
    blurb: '시안 공유, 피드백, 수정 요청',
    cards: [
      { ko: '시안 두 가지로 준비해 봤습니다', en: "I've put together two directions.", situation: '시안 공유', context: [] },
      { ko: '피드백 주시면 반영하겠습니다', en: "Send over your feedback and I'll work it in.", situation: '피드백 요청', context: [] },
      { ko: '어떤 점이 아쉬우신지 조금 더 구체적으로 말씀해 주실 수 있을까요?', en: 'Could you be a bit more specific about what feels off?', situation: '피드백 구체화', context: [{ speaker: '팀장', text: '뭔가 좀 아쉬운데요' }] },
      { ko: '그렇게 하면 다른 화면이랑 안 맞아요', en: "That would break consistency with the other screens.", situation: '이견 제시', context: [] },
      { ko: '수정본 올려두었습니다', en: "I've uploaded the revised version.", situation: '수정 완료', context: [] },
      { ko: '이 버전이 더 나은 것 같아요', en: 'I think this version works better.', situation: '의견 제시', context: [] },
      { ko: '개발 가능한지 먼저 확인해 볼게요', en: "Let me check whether this is feasible to build.", situation: '실현성 확인', context: [] },
      { ko: '레퍼런스 몇 개 공유드립니다', en: 'Sharing a few references here.', situation: '참고자료 전달', context: [] },
      { ko: '조금만 더 시간 주시면 정리해서 드릴게요', en: 'Give me a bit more time and I\'ll have it cleaned up.', situation: '시간 요청', context: [] },
      { ko: '여기는 의도한 겁니다', en: "That part is intentional.", situation: '의도 설명', context: [{ speaker: '팀장', text: '여기 간격이 좀 넓지 않나요?' }] },
      { ko: '최종본으로 확정해도 될까요?', en: 'Can we lock this in as final?', situation: '확정 요청', context: [] },
      { ko: '에셋 전달드렸습니다', en: "I've handed off the assets.", situation: '전달 완료', context: [] },
      { ko: '초안이라 아직 러프합니다', en: "It's rough — this is a first pass.", situation: '상태 안내', context: [] },
      { ko: '방향만 먼저 봐주세요', en: 'Just look at the direction for now.', situation: '검토 범위', context: [] },
      { ko: '색은 아직 확정 아닙니다', en: "The colors aren't final yet.", situation: '미확정', context: [] },
      { ko: '폰트는 이걸로 통일했습니다', en: "I've standardized on this typeface.", situation: '결정 설명', context: [] },
      { ko: '간격 규칙을 하나로 맞췄어요', en: "I've unified the spacing rules.", situation: '정리 설명', context: [] },
      { ko: '모바일에서는 이렇게 보입니다', en: "Here's how it looks on mobile.", situation: '대응 설명', context: [] },
      { ko: '작은 화면에서는 두 줄로 내려갑니다', en: 'On a small screen it wraps to two lines.', situation: '반응형', context: [] },
      { ko: '다크 모드도 같이 준비했습니다', en: "I've done a dark mode pass as well.", situation: '범위 확대', context: [] },
      { ko: '접근성 때문에 대비를 높였어요', en: 'I raised the contrast for accessibility.', situation: '근거 설명', context: [{ speaker: '팀장', text: '이 회색 좀 진해지지 않았나요?' }] },
      { ko: '아이콘은 라이브러리에서 가져왔습니다', en: 'The icons come from our library.', situation: '출처 안내', context: [] },
      { ko: '라이선스 확인했습니다', en: 'I checked the license.', situation: '확인 완료', context: [] },
      { ko: '이 안은 버리는 게 좋을 것 같아요', en: 'I think we should drop this one.', situation: '안 폐기', context: [] },
      { ko: '두 개를 섞으면 애매해집니다', en: 'Mixing the two makes it muddy.', situation: '이견 제시', context: [{ speaker: '팀장', text: 'A안이랑 B안 좋은 것만 합치면 안 될까요?' }] },
      { ko: '하나만 고르시면 그쪽으로 밀겠습니다', en: "Pick one and I'll push it all the way.", situation: '결정 요청', context: [] },
      { ko: '취향 문제인지 기준 문제인지 알고 싶어요', en: 'Is this a preference or a requirement?', situation: '피드백 분류', context: [] },
      { ko: '그 기준이면 이렇게 가야 합니다', en: "If that's the standard, this is the way to go.", situation: '기준 적용', context: [] },
      { ko: '수정은 두 번까지 가능합니다', en: 'I can do two rounds of revisions.', situation: '범위 합의', context: [] },
      { ko: '언제까지 드리면 될까요?', en: 'When do you need this by?', situation: '마감 확인', context: [] },
      { ko: '개발자분과 같이 보면 빠를 것 같아요', en: "It'd go faster if engineering looked at it with us.", situation: '협업 제안', context: [] },
      { ko: '스펙 문서 링크 주실 수 있을까요?', en: 'Could you send me the spec?', situation: '자료 요청', context: [] },
      { ko: '화면이 몇 개인지부터 알아야 합니다', en: 'I need to know how many screens first.', situation: '범위 확인', context: [] },
      { ko: '이 흐름이 한 단계 더 깁니다', en: 'This flow has one step too many.', situation: '문제 지적', context: [] },
      { ko: '한 단계 줄여봤습니다', en: 'I cut it down by one step.', situation: '개선 보고', context: [] },
      { ko: '실제 데이터로 한 번 넣어볼게요', en: 'Let me drop in real data and see how it holds.', situation: '검증 시도', context: [] },
      { ko: '텍스트가 길어지면 깨집니다', en: 'It breaks when the text runs long.', situation: '리스크 경고', context: [] },
      { ko: '예외 케이스도 그려두었습니다', en: "I've drawn the edge cases too.", situation: '범위 설명', context: [] },
      { ko: '프로토타입 링크 공유드립니다', en: 'Sharing the prototype link.', situation: '전달', context: [] },
      { ko: '피드백은 금요일까지 부탁드려요', en: 'Could I get feedback by Friday?', situation: '마감 요청', context: [] },
    ],
  },
];

/** Deck by id, or undefined. */
export const findDeck = (id) => JOB_DECKS.find((d) => d.id === id);
